### PR TITLE
Event.persisted? is potentially misleading

### PR DESCRIPTION
**Pull request by andyjdavis**
re https://github.com/envato/event_sourcery/issues/180

Event.persisted? actually just checks if the event has an ID. That behaviour may be surprising. I'm not sure what the best solution is currently however I have written a small test that clearly demonstrates the issue.

### CODE REVIEW

**Comment by domon-envato** [comment]
> Event.persisted? actually just checks if the event has an ID.

How is this method used?

I quickly searched the term `persisted` in `event_sourcery` and `event_sourcery-postgres` but could not find any usage of this method.

Can we potentially remove this method?

**Comment by andyjdavis** [comment]
I am certainly open to simply removing the persisted? method. It seems rather low value with event_sourcery users being able to replicate its functionality very easily
```
# Is this event persisted?
    def persisted?
      !id.nil?
    end
```
I will repurpose this PR to remove the event.persisted? method.

Simultaneously I plan to bump the version to 1.0.0 as the removal of persisted? is a breaking change.

**Comment by andyjdavis** [comment]
I have updated this PR to just remove Event.persisted?

I needed to bump the version and, barring any objections, I suggest that we go to 1.0.0. Removing Event.persisted? is a small changed but is a breaking change.

Related to going to 1.0.0 I have updated the readme to have a `development status` similar to the readme in https://github.com/envato/rack-ecg/ and removed the text about this repo undergoing rapid development (which isn't accurate).

**Review by domon-envato — APPROVED** [review]
LGTM

**Pull request merged**
