### PR TITLE
Upcasters

### PR DESCRIPTION
**Pull request by stevehodgkiss**
Upcasters are a function applied to event bodies of a given type. Multiple can be defined for a given type and they're executed in the order they're defined. Useful when the schema changes and in order to fill in default values to avoid spreading the default knowledge across the event consumers.

### CODE REVIEW

**Comment by twe4ked** [comment]
A simple `dup` on the hash won't work with nested hashes.

**Comment by twe4ked** [comment]
We've been using upcasting with Event Sourcery for a while by overriding our `EventBuilder`:

``` ruby
class EventBuilder
  def initialize(event_type_serializer:)
    @event_type_serializer = event_type_serializer
  end

  def build(event_data)
    type = event_data.fetch(:type)
    klass = event_type_serializer.deserialize(type)
    upcast(klass.new(event_data))
  end

  private

  attr_reader :event_type_serializer

  def upcast(event)
    if event.class.respond_to?(:upcast)
      event.class.upcast(event)
    else
      event
    end
  end
end
```

Example usage:

``` ruby
# event definition
TodoCreated = Class.new(EventSourcery::Event) do
  def self.upcast(event)
    body['content_type'] ||= 'photo'
    event.with(body: body)
  end
end
```

**Comment by stevehodgkiss** [comment]
@twe4ked nice. Perhaps a default implementation of `.upcast` could return `self` to avoid having to use `respond_to?`. Do you want to make a PR with that approach?

**Comment by twe4ked** [comment]
> Perhaps a default implementation of .upcast could return self to avoid having to use respond_to?. Do you want to make a PR with that approach?

Yeah I did consider that. Feel free to PR it or I'm happy to. Let me know :)

**Comment by stevehodgkiss** [comment]
@twe4ked I'm happy for you to make the PR when you have time 😜

**Pull request closed without merging**
